services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - backend/.env

  rust:
    build: ./bridges/rust
    restart: always

  cpp:
    build: ./bridges/cpp
    restart: always

  node-api:
    build: ./bridges/node
    ports:
      - '4000:4000'
    restart: always
    depends_on:
      - backend
