name: Multi-Language Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Install Python Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Build Rust Code
        run: |
          cd bridges/rust
          cargo build --release

      - name: Compile C++ Code
        run: |
          g++ -shared -o bridges/cpp/libcompute.so -fPIC bridges/cpp/compute.cpp

      - name: Install Node.js Dependencies
        run: |
          cd bridges/node
          npm install

      - name: Build and Run Docker Containers
        run: |
          docker-compose build
          docker-compose up -d